### ISSUE TITLE
HU1: Identificación de Intenciones en Lenguaje Natural

### ISSUE THREAD

**Issue by benjaminriveros** [INF225-2023-2-P201/06-mereketengue#2]
"Como usuario, quiero que la red identifique la intención usando lenguaje natural".
**Criterio aceptación:** Dado un usuario que se comunique con la red en lenguaje natural, cuando la red procese la entrada del usuario, entonces debe ser capaz de identificar la intención del usuario.

**Comment by guteh** [comment]
Se implementa codigo que identifica tipos de palabras segun una frase dada, y lo relaciona con un entorno de red.

**Comment by guteh** [comment]
- Se crea una carpeta Historial, donde se guardan las acciones en un .txt ,con formato nombre de la fecha y hora de la acción 
- Se agregan adverbios de negación reconocibles y se agregan palabras que inicien el comando de bloquear internet
- Se mejora el código para guardar el nombre del nodo o la ip
- Se agrega el comando de hacer ping
