### ISSUE TITLE
HU2: Aplicación de Políticas de Seguridad en la Red

### ISSUE THREAD

**Issue by benjaminriveros** [INF225-2023-2-P201/06-mereketengue#3]
Como un gerente de seguridad, quiero tener la capacidad de aplicar políticas de seguridad específicas en la red para garantizar la integridad de los datos y proteger contra amenazas cibernéticas.
**Criterio aceptación:** Dado un administrador de red con la intención de aplicar políticas de seguridad específicas, cuando configure y aplique estas políticas en la red, entonces las políticas deben garantizar la integridad de los datos y proteger contra amenazas cibernéticas.

**Comment by guteh** [comment]
Se implementa interfaz para poder realizar modificaciones a la red a partir de lenguaje natural.

**Comment by guteh** [comment]
Se agrega a interfaz un historial de acciones realizadas.
