### ISSUE TITLE
HU5: Personalización de la Red según las Intenciones del Usuario

### ISSUE THREAD

**Issue by benjaminriveros** [INF225-2023-2-P201/06-mereketengue#6]
"Como usuario, quiero tener una red que pueda ser modificada según mis intenciones​".
**Criterio aceptación:** Dado un usuario que desee modificar la configuración de la red, cuando el usuario realice cambios en la configuración, entonces los cambios deben reflejarse efectivamente en la operación de la red de acuerdo con las intenciones del usuario.

**Comment by guteh** [comment]
Se implementa un entorno de red que pueda ser modificado, compuesto por 1 router, 2 switch y un firewall.
