### ISSUE TITLE
HU3: Implementacion base de datos para red.

### ISSUE THREAD

**Issue by guteh** [INF225-2023-2-P201/06-mereketengue#7]
HU: Como administrador de red quiero una base de datos para poder manejar el tráfico de la red.

Criterio de aceptación: Base de datos es implementada con toda la información disponible relacionada a la red.

**Comment by guteh** [comment]
Se crea base de datos en mysql, con 3 tablas router, firewall y pc/server. Cada tabla es completada con datos para probar funcionamiento

**Comment by benjaminriveros** [comment]
Se logró la mejora de interfaz, aumento de restricciones, una nueva funcionalidad "ping" y palabras claves para el reconocimiento.

**Comment by benjaminriveros** [comment]
Problemas para lograr la conexión el interpretador y la DB.

**Comment by benjaminriveros** [comment]
Conexión lista.
